### ISSUE TITLE
Handler AJAX 'onInspectableGetOptions' not found

### ISSUE THREAD

**Issue by amdad** [toughdeveloper/oc-richeditorsnippets-plugin#3]
Hello Matthew, 
thanks for great plugin, both with resizer are things that I missed in October. You resolve it!

Unfortunately, I got error on more advanced components to be loaded. For example I registered Rainlab.Blog components as snippets. And in Pages plugin it works without error, but outside Pages plugin where your plugin take a lead I got this error about missing: Handler AJAX 'onInspectableGetOptions' after click on added snippet in editor to edit params.

Original post: http://octobercms.com/plugin/support/toughdeveloper-richeditorsnippets/handler-ajax-oninspectablegetoptions-not-found

**Comment by matt-pawley** [comment]
Hi thanks for using the plugin. I'm currently away with very little internet access. I'm back Tuesday and will look into it ASAP. If you need an urgent fix the additional method likely needs adding to the boot method of plugin.php where the controller has been extended.

Thanks

**Comment by amdad** [comment]
Thanks for reply, I'm a beginner dev, so I'll wait to see it done right and test it.

**Comment by matt-pawley** [comment]
Hi, this should now be fixed as of v1.0.3.

**Comment by amdad** [comment]
Yes, I checked, it works. I will continue testing to be sure everything works well. THANKS!
